ALTER TABLE sites ADD COLUMN total_requests INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sites ADD COLUMN total_bytes_out INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sites ADD COLUMN storage_bytes INTEGER NOT NULL DEFAULT 0;
