name = "oauth-page-worker"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_URL = "https://app.oauth.page"
BETA_ONE_TIME_LINKS = "true" # easy launch toggle: set to "false"
# Set these as secrets via `wrangler secret put`:
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET
# JWT_SECRET
# RESEND_API_KEY

[[d1_databases]]
binding = "DB"
database_name = "oauth-page-db"
database_id = "d3fe89b5-4259-45ea-b344-77d6c26cbe8a"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "b651495a73a04699a0d14cef9af8df2d"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "oauthpage-sites"

[browser]
binding = "BROWSER"

[[routes]]
pattern = "*.oauth.page/*"
zone_name = "oauth.page"

[[routes]]
pattern = "oauth.page/*"
zone_name = "oauth.page"
